// Fantaszy Szentre local data adapter
// GitHub Pages cannot call the FPL API directly from Safari because of CORS.
// This intercepts those requests and serves JSON snapshots generated by GitHub Actions.
(() => {
  const nativeFetch = window.fetch.bind(window);
  const FPL_ORIGIN = 'https://fantasy.premierleague.com/api';

  function localPath(url) {
    if (!url || !url.startsWith(FPL_ORIGIN)) return null;
    const path = url.slice(FPL_ORIGIN.length);

    if (path === '/bootstrap-static/' || path === '/bootstrap-static') {
      return './data/bootstrap-static.json';
    }
    if (path === '/fixtures/' || path === '/fixtures') {
      return './data/fixtures.json';
    }

    let m = path.match(/^\/entry\/(\d+)\/?$/);
    if (m) return `./data/entry/${m[1]}.json`;

    m = path.match(/^\/entry\/(\d+)\/history\/?$/);
    if (m) return `./data/entry/${m[1]}/history.json`;

    m = path.match(/^\/entry\/(\d+)\/transfers\/?$/);
    if (m) return `./data/entry/${m[1]}/transfers.json`;

    m = path.match(/^\/entry\/(\d+)\/event\/(\d+)\/picks\/?$/);
    if (m) return `./data/entry/${m[1]}/event/${m[2]}/picks.json`;

    return null;
  }

  window.fetch = async (input, init = {}) => {
    const url = typeof input === 'string' ? input : input?.url;
    const mapped = localPath(url);
    if (!mapped) return nativeFetch(input, init);

    const forceFresh = init?.cache === 'no-store';
    const finalUrl = forceFresh ? `${mapped}?v=${Date.now()}` : mapped;
    return nativeFetch(finalUrl, { ...init, headers: { Accept: 'application/json' } });
  };
})();
