// Fantaszy Szentre local data adapter — canonical squad / Free Hit aware
// GitHub Pages cannot call the FPL API directly from Safari because of CORS.
// This adapter serves local JSON snapshots generated by GitHub Actions.
// IMPORTANT: for My Team planning, a Free Hit event must revert to the latest
// non-Free-Hit permanent squad BEFORE app.js / owner-ui-30.js see the picks.
(() => {
  'use strict';

  const VERSION = '20260918-canonical-engine1';
  const nativeFetch = window.fetch.bind(window);
  const FPL_ORIGIN = 'https://fantasy.premierleague.com/api';

  const historyCache = new Map();
  const bootstrapCache = { value: null };
  const resolutions = new Map();

  const n = v => Number(v || 0);

  function sharedEngine() {
    return window.FantaszySzentreEngine || null;
  }

  function isFreeHitName(value) {
    return Boolean(sharedEngine()?.isFreeHitName?.(value));
  }

  function localPath(url) {
    if (!url || !url.startsWith(FPL_ORIGIN)) return null;
    const path = url.slice(FPL_ORIGIN.length);

    if (path === '/bootstrap-static/' || path === '/bootstrap-static') {
      return './data/bootstrap-static.json';
    }
    if (path === '/fixtures/' || path === '/fixtures') {
      return './data/fixtures.json';
    }

    let m = path.match(/^\/entry\/(\d+)\/?$/);
    if (m) return `./data/entry/${m[1]}.json`;

    m = path.match(/^\/entry\/(\d+)\/history\/?$/);
    if (m) return `./data/entry/${m[1]}/history.json`;

    m = path.match(/^\/entry\/(\d+)\/transfers\/?$/);
    if (m) return `./data/entry/${m[1]}/transfers.json`;

    m = path.match(/^\/entry\/(\d+)\/event\/(\d+)\/picks\/?$/);
    if (m) return `./data/entry/${m[1]}/event/${m[2]}/picks.json`;

    return null;
  }

  function parsePicksRequest(url) {
    if (!url || !url.startsWith(FPL_ORIGIN)) return null;
    const path = url.slice(FPL_ORIGIN.length);
    const m = path.match(/^\/entry\/(\d+)\/event\/(\d+)\/picks\/?$/);
    if (!m) return null;
    return { entryId: Number(m[1]), gw: Number(m[2]) };
  }

  function responseJSON(data, status = 200) {
    return new Response(JSON.stringify(data), {
      status,
      headers: {
        'content-type': 'application/json; charset=utf-8',
        'cache-control': 'no-store, max-age=0'
      }
    });
  }

  async function fetchLocalJSON(path, forceFresh = false) {
    const finalUrl = forceFresh
      ? `${path}${path.includes('?') ? '&' : '?'}v=${Date.now()}`
      : path;

    try {
      const res = await nativeFetch(finalUrl, {
        cache: forceFresh ? 'no-store' : 'default',
        headers: { Accept: 'application/json' }
      });
      if (!res.ok) return null;
      return await res.json();
    } catch {
      return null;
    }
  }

  async function getHistory(entryId, forceFresh = false) {
    const key = Number(entryId);
    if (!forceFresh && historyCache.has(key)) return historyCache.get(key);

    const data = await fetchLocalJSON(
      `./data/entry/${key}/history.json`,
      forceFresh
    );

    if (data) historyCache.set(key, data);
    return data;
  }

  async function getBootstrap(forceFresh = false) {
    if (!forceFresh && bootstrapCache.value) return bootstrapCache.value;
    const data = await fetchLocalJSON('./data/bootstrap-static.json', forceFresh);
    if (data) bootstrapCache.value = data;
    return data;
  }

  function freeHitEvents(history) {
    return sharedEngine()?.freeHitEvents?.(history) || new Set();
  }

  function validPicks(data) {
    return Boolean(data && Array.isArray(data.picks) && data.picks.length === 15);
  }

  async function findPermanentSource(entryId, freeHitGw, current, history, forceFresh) {
    const engine = sharedEngine();
    if (!engine?.resolveCanonicalSquad) return null;

    const candidates = [];
    for (let gw = Number(freeHitGw) - 1; gw >= 1; gw--) {
      const prior = await fetchLocalJSON(
        `./data/entry/${entryId}/event/${gw}/picks.json`,
        forceFresh
      );

      if (!validPicks(prior)) continue;
      candidates.push({gw, data:prior});

      const resolved = engine.resolveCanonicalSquad({
        entryId,
        requestedGw:freeHitGw,
        current,
        history,
        priorCandidates:candidates
      });

      if (resolved?.ok && resolved?.reverted && resolved?.source) {
        return {gw:resolved.sourceGw, data:resolved.source};
      }
    }
    return null;
  }

  function sellingPrice(purchasePrice, currentPrice) {
    const purchase = n(purchasePrice);
    const current = n(currentPrice);

    if (!purchase) return current;
    if (!current) return purchase;
    if (current <= purchase) return current;

    return purchase + Math.floor((current - purchase) / 2);
  }

  async function refreshPermanentSellingPrices(picks, forceFresh) {
    const bootstrap = await getBootstrap(forceFresh);
    const nowCost = new Map(
      (bootstrap?.elements || []).map(p => [Number(p.id), Number(p.now_cost || 0)])
    );

    let total = 0;
    const refreshed = (picks || []).map(p => {
      const current = nowCost.get(Number(p.element)) || Number(p.selling_price || 0);
      const selling = sellingPrice(p.purchase_price, current);
      total += selling;
      return { ...p, selling_price: selling };
    });

    return { picks: refreshed, squadSellingValue: total };
  }

  async function canonicalisePicks(entryId, gw, current, forceFresh) {
    const history = await getHistory(entryId, forceFresh);
    const engine = sharedEngine();

    if (!engine?.resolveCanonicalSquad) {
      resolutions.set(`${entryId}:${gw}`, {
        entryId, requestedGw:gw, sourceGw:null, reverted:false,
        error:'FS_ENGINE_CANONICAL_RESOLVER_UNAVAILABLE'
      });
      return null;
    }

    const initial = engine.resolveCanonicalSquad({
      entryId, requestedGw:gw, current, history, priorCandidates:[]
    });

    if (initial?.ok && !initial?.reverted) {
      resolutions.set(`${entryId}:${gw}`, {
        entryId, requestedGw:gw, sourceGw:gw, reverted:false
      });
      return current;
    }

    const source = await findPermanentSource(
      entryId, gw, current, history, forceFresh
    );

    // Trust rule: never pass a one-week Free Hit squad into planning if
    // the permanent source cannot be established.
    if (!source) {
      resolutions.set(`${entryId}:${gw}`, {
        entryId, requestedGw:gw, sourceGw:null, reverted:false,
        error:'FREE_HIT_PERMANENT_SQUAD_UNAVAILABLE'
      });
      return null;
    }

    const finance = await refreshPermanentSellingPrices(
      source.data.picks,
      forceFresh
    );

    const permanentBank =
      source.data?.entry_history?.bank ??
      current?.entry_history?.bank ??
      0;

    const currentHistory = current?.entry_history || {};
    const effective = {
      ...current,

      // Permanent 15 only.
      picks: finance.picks,

      // The current published GW remains useful for points/rank context,
      // but the chip itself must not leak into next-GW planning.
      active_chip: null,

      _fs_original_active_chip: current?.active_chip || 'freehit',
      _fs_freehit_reversion: {
        version: VERSION,
        entry_id: Number(entryId),
        freehit_event: Number(gw),
        permanent_source_event: Number(source.gw),
        verified_from: 'local_entry_history',
        resolved_at: new Date().toISOString()
      },

      entry_history: {
        ...currentHistory,
        bank: Number(permanentBank),
        value: finance.squadSellingValue
          ? finance.squadSellingValue + Number(permanentBank)
          : (source.data?.entry_history?.value ?? currentHistory.value ?? 0),

        // FH transfer activity is not a permanent transfer plan.
        event_transfers: 0,
        event_transfers_cost: 0
      }
    };

    resolutions.set(`${entryId}:${gw}`, {
      entryId,
      requestedGw: Number(gw),
      sourceGw: Number(source.gw),
      reverted: true,
      freeHitGw: Number(gw),
      elements: effective.picks.map(p => Number(p.element))
    });

    return effective;
  }

  // app.js caches FPL payloads in localStorage for ~20 minutes.
  // Remove only squad/history caches once when this adapter version changes,
  // otherwise an old FH squad can bypass this adapter entirely.
  try {
    const versionKey = 'fs:data-adapter-version';
    if (localStorage.getItem(versionKey) !== VERSION) {
      for (const key of Object.keys(localStorage)) {
        if (
          key.startsWith('fs:/entry/') &&
          (key.includes('/picks/') || key.endsWith('/history/') || key.endsWith('/history'))
        ) {
          localStorage.removeItem(key);
        }
      }
      localStorage.setItem(versionKey, VERSION);
    }
  } catch {}

  window.fetch = async (input, init = {}) => {
    const url = typeof input === 'string' ? input : input?.url;
    const mapped = localPath(url);

    if (!mapped) return nativeFetch(input, init);

    const forceFresh = init?.cache === 'no-store';
    const parsed = parsePicksRequest(url);

    // Ordinary local FPL snapshot.
    if (!parsed) {
      const finalUrl = forceFresh ? `${mapped}?v=${Date.now()}` : mapped;
      return nativeFetch(finalUrl, {
        ...init,
        headers: { ...(init?.headers || {}), Accept: 'application/json' }
      });
    }

    // Picks endpoint: inspect the local published picks and canonicalise FH.
    const current = await fetchLocalJSON(mapped, forceFresh);

    if (!validPicks(current)) {
      return responseJSON(
        { error: 'PICKS_SNAPSHOT_UNAVAILABLE', entry_id: parsed.entryId, event: parsed.gw },
        404
      );
    }

    const effective = await canonicalisePicks(
      parsed.entryId,
      parsed.gw,
      current,
      forceFresh
    );

    if (!effective) {
      // Safer to make this team unavailable than to recommend from a temporary FH 15.
      return responseJSON(
        {
          error: 'FREE_HIT_PERMANENT_SQUAD_UNAVAILABLE',
          entry_id: parsed.entryId,
          event: parsed.gw
        },
        409
      );
    }

    return responseJSON(effective, 200);
  };

  window.FSDataAdapter = {
    version: VERSION,
    audit() {
      return [...resolutions.values()].map(x => ({ ...x }));
    }
  };
})();
